# Development Container
FROM ddsdok/gotask

# Install ddsgok packages
RUN go get github.com/ddsgok/colog/...
RUN go get github.com/ddsgok/gql/...
RUN go get github.com/ddsgok/log/...
RUN go get github.com/ddsgok/str/...
RUN go get github.com/ddsgok/bdd/...

# Install ddsgok related
RUN go get github.com/mgutz/ansi/...

# Install gRPC related packages
RUN go get github.com/golang/protobuf/...
RUN go get google.golang.org/grpc/...
RUN go get google.golang.org/genproto/...

# Install cobra related packages
RUN go get github.com/spf13/cobra/...
RUN go get github.com/spf13/pflag/...
RUN go get github.com/pkg/errors/...
RUN go get github.com/xordataexchange/crypt/...